### ISSUE TITLE
Import references README

### ISSUE THREAD

**Issue by Peggaweng** [EricFromCanada/ericfromcanada.github.io#1]
Hi,

I am trying out your really cool script to import the certificates to the keychain and for some reason I get this

Error opening input file /etc/letsencrypt/live/README/cert.pem
/etc/letsencrypt/live/README/cert.pem: Not a directory
Unable to delete certificate matching "-t"security: Error reading infile /etc/letsencrypt/live/README/letsencrypt_sslcert.p12: Not a directory
Unable to delete certificate matching "-t"1 identity imported.

Why is it trying to read from the README as a path?

Can you help please?

Thanks in advance

**Comment by EricFromCanada** [comment]
The line `for PEM_FOLDER in /etc/letsencrypt/live/*` iterates through each item in `/etc/letsencrypt/live`, but it assumes everything in there is a folder. Apparently cerbot puts a README in there now. Move that file elsewhere and it should work. Later I'll look into modifying it so it only iterates through directories.

**Comment by Peggaweng** [comment]
Thank you 😊
